# Generated by Django 3.0.1 on 2020-07-11 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalScore', models.IntegerField()),
                ('name', models.TextField(help_text='Enter a name for this game')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Enter Your Username: ')),
                ('email', models.EmailField(help_text='Enter Your Email', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerInGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='games',
            field=models.ManyToManyField(through='games.PlayerInGame', to='games.Game'),
        ),
    ]
