# Generated by Django 3.0.1 on 2020-07-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(through='games.PlayerInGame', to='games.Player'),
        ),
    ]
