# Generated by Django 3.0.1 on 2020-07-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='totalScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playeringame',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
