# Generated by Django 3.0.1 on 2020-07-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20200713_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='password',
            field=models.CharField(default='password', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=1000, verbose_name="what's the name of the game?"),
        ),
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.EmailField(help_text='Enter Your Email: ', max_length=254),
        ),
    ]
